"""Builds public/i18n/<lang>.js from tools/i18n/<lang>.py (+ errors_<lang>.py) and checks them.
   python tools/build_i18n.py          # build + report problems
Checks: every static t('key') used in public/js exists in English; every language has every key; {placeholders} match English."""
import importlib
import json
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.insert(0, os.path.join(ROOT, 'tools', 'i18n'))
LANGS = ['en', 'lv', 'ru', 'uk']
PH = re.compile(r'\{(\w+)\}')

en = importlib.import_module('en').T
errors_en = importlib.import_module('errors_en').ERR
problems = 0

# ---- static keys used by the front end must exist
used = set()
dynamic_ok = ('guide.', 'q.', 'a.', 'n.', 'eff.', 'kind.', 'shop.', 'role.', 'status.', 'task.', 'hide.role_', 'hide.outcome_', 'cat.', 'adminmode.', 'rarity.', 'ed.p_', 'gps.err_', 'conn.', 'mode.', 'ap.')
for fn in os.listdir(os.path.join(ROOT, 'public', 'js')):
    if fn.endswith('.js'):
        src = open(os.path.join(ROOT, 'public', 'js', fn), encoding='utf8').read()
        used.update(re.findall(r"\bt\('([a-zA-Z0-9_.\-]+)'", src))
for k in sorted(used):
    if k not in en and not k.endswith(('.', '_')):
        print('MISSING in en:', k); problems += 1

os.makedirs(os.path.join(ROOT, 'public', 'i18n'), exist_ok=True)
for lang in LANGS:
    T = dict(en) if lang == 'en' else {}
    if lang != 'en':
        T = dict(importlib.import_module(lang).T)
        for k in en:
            if k not in T:
                print('[%s] missing %s' % (lang, k)); problems += 1
            elif set(PH.findall(T[k])) != set(PH.findall(en[k])):
                print('[%s] placeholder mismatch %s: %r vs %r' % (lang, k, T[k], en[k])); problems += 1
        for k in T:
            if k not in en:
                print('[%s] unknown key %s' % (lang, k)); problems += 1
    E = {}
    if lang != 'en':
        try:
            E = importlib.import_module('errors_' + lang).E
        except ImportError:
            print('[%s] no errors file' % lang); problems += 1
    for k, tpl in errors_en.items():
        if lang == 'en':
            T[k] = tpl
        elif tpl in E:
            if set(PH.findall(E[tpl])) != set(PH.findall(tpl)):
                print('[%s] error placeholder mismatch: %r' % (lang, tpl)); problems += 1
            T[k] = E[tpl]
        else:
            print('[%s] untranslated error: %r' % (lang, tpl)); problems += 1
    with open(os.path.join(ROOT, 'public', 'i18n', lang + '.js'), 'w', encoding='utf8') as f:
        f.write('/* generated by tools/build_i18n.py - do not edit by hand */\n(self.JLL_LOCALES = self.JLL_LOCALES || {}).%s = %s;\n' % (lang, json.dumps(T, ensure_ascii=False, indent=0, sort_keys=True)))
    print('%s: %d keys' % (lang, len(T)))
print('problems:', problems)
sys.exit(1 if problems else 0)
