"""Extracts every user-visible server error message (GameError) so the client can translate it.
Writes public/js/errors.js (regex -> key) and tools/i18n/errors_en.py (key -> English template with {1}, {2} placeholders)."""
import ast
import glob
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
FMT = re.compile(r'%(?:\.\d+)?[sdf]')
msgs = {}


def add(fmt):
    msgs.setdefault(fmt, None)


for path in sorted(glob.glob(os.path.join(ROOT, 'server', '*.py'))):
    tree = ast.parse(open(path, encoding='utf8').read())
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and getattr(node.func, 'id', None) == 'GameError' and node.args:
            a = node.args[0]
            if isinstance(a, ast.Constant) and isinstance(a.value, str):
                add(a.value)
            elif isinstance(a, ast.BinOp) and isinstance(a.op, ast.Mod) and isinstance(a.left, ast.Constant):
                add(a.left.value)
            elif isinstance(a, ast.BinOp) and isinstance(a.op, ast.Add):
                # 'x' + y + 'z' -> keep the literal pieces joined with a placeholder
                parts = []

                def walk(n):
                    if isinstance(n, ast.BinOp) and isinstance(n.op, ast.Add):
                        walk(n.left), walk(n.right)
                    elif isinstance(n, ast.Constant):
                        parts.append(n.value)
                    else:
                        parts.append('%s')
                walk(a)
                add(''.join(parts))

fmts = sorted(msgs)
# the server's validators build 'Name must be at least 2 characters' etc. from variables - listed explicitly
extra = ['The game is paused', 'Your GPS position is not fresh yet - wait a few seconds with location sharing on', "The hider's GPS position is not fresh yet - wait a few seconds", '%s must be at least 2 characters', '%s must be between %s and %s', '%s must be a number', 'Server error: %r']
for e in extra:
    if e not in fmts:
        fmts.append(e)

lines, en = [], []
for i, f in enumerate(fmts, 1):
    n = [0]

    def sub(m):
        n[0] += 1
        return '{%d}' % n[0]
    template = FMT.sub(sub, f.replace('%r', '%s'))
    pattern = re.escape(FMT.sub('\x00', f.replace('%r', '%s'))).replace('\x00', '(.+?)')
    lines.append((pattern, str(i)))
    en.append((str(i), template))

os.makedirs(os.path.join(ROOT, 'tools', 'i18n'), exist_ok=True)
with open(os.path.join(ROOT, 'public', 'js', 'errors.js'), 'w', encoding='utf8') as f:
    f.write('// generated by tools/extract_errors.py - server error message patterns -> translation keys (e.<key>)\nexport const ERRORS = [\n')
    for p, k in lines:
        f.write("  [%s, '%s'],\n" % (repr(p).replace('\\\\', '\\\\'), k))
    f.write('];\n')
with open(os.path.join(ROOT, 'tools', 'i18n', 'errors_en.py'), 'w', encoding='utf8') as f:
    f.write('# generated by tools/extract_errors.py\nERR = {\n')
    for k, v in en:
        f.write('    %r: %r,\n' % ('e.' + k, v))
    f.write('}\n')
print(len(fmts), 'messages')
