"""Downloads the self-hosted fonts (fontsource CDN, SIL OFL) and writes public/css/fonts.css.
Every family covers Latin, Latin-Extended (Latvian, Lithuanian, Estonian, German) and Cyrillic (Russian, Ukrainian)."""
import os
import urllib.request

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'public')
FONTS = os.path.join(ROOT, 'vendor', 'fonts')
BASE = 'https://cdn.jsdelivr.net/fontsource/fonts/%s@latest/%s-%s-normal.woff2'
FAMILIES = {  # css name -> (fontsource id, weights)
    'M PLUS Rounded 1c': ('m-plus-rounded-1c', (700, 800)),
    'Nunito': ('nunito', (400, 700)),
    'Lora': ('lora', (400, 700)),
    'Source Sans 3': ('source-sans-3', (400, 700)),
    'Comfortaa': ('comfortaa', (400, 700)),
    'Unbounded': ('unbounded', (700,)),
    'Rubik': ('rubik', (400, 700)),
    'Cormorant Garamond': ('cormorant-garamond', (700,)),
    'JetBrains Mono': ('jetbrains-mono', (400, 700)),
    'Playfair Display': ('playfair-display', (700,)),
    'IBM Plex Sans': ('ibm-plex-sans', (400, 700)),
}
RANGES = {
    'latin': 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
    'latin-ext': 'U+0100-02AF,U+0304,U+0308,U+0329,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF',
    'cyrillic': 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116',
}

os.makedirs(FONTS, exist_ok=True)
for f in os.listdir(FONTS):
    os.remove(os.path.join(FONTS, f))
css = ['/* generated by tools/fetch_fonts.py - self-hosted, SIL Open Font License. A font file is only downloaded when a theme uses it. */']
for name, (fid, weights) in FAMILIES.items():
    for w in weights:
        for sub, rng in RANGES.items():
            fn = '%s-%s-%d.woff2' % (fid, sub, w)
            with urllib.request.urlopen(BASE % (fid, sub, w)) as r, open(os.path.join(FONTS, fn), 'wb') as out:
                out.write(r.read())
            css.append("@font-face{font-family:'%s';font-weight:%d;font-display:swap;src:url(/vendor/fonts/%s) format('woff2');unicode-range:%s}" % (name, w, fn, rng))
with open(os.path.join(ROOT, 'css', 'fonts.css'), 'w', encoding='utf8') as f:
    f.write('\n'.join(css) + '\n')
total = sum(os.path.getsize(os.path.join(FONTS, f)) for f in os.listdir(FONTS))
print('%d files, %.0f KB total (only the active theme\'s fonts are fetched by a browser)' % (len(os.listdir(FONTS)), total / 1024))
